const foods = [
  // ── Carnes & Aves ─────────────────────────────────────────────────────────
  { cat: "Carnes & Aves", nome: "Peito de frango grelhado",        cal: 165, prot: 31.0, carb: 0.0,  fat: 3.6  },
  { cat: "Carnes & Aves", nome: "Frango inteiro assado",           cal: 215, prot: 29.0, carb: 0.0,  fat: 11.0 },
  { cat: "Carnes & Aves", nome: "Coxa de frango sem pele",         cal: 177, prot: 25.0, carb: 0.0,  fat: 8.2  },
  { cat: "Carnes & Aves", nome: "Frango desfiado cozido",          cal: 159, prot: 30.0, carb: 0.0,  fat: 4.0  },
  { cat: "Carnes & Aves", nome: "Coração de frango",               cal: 148, prot: 21.0, carb: 0.0,  fat: 7.0  },
  { cat: "Carnes & Aves", nome: "Alcatra grelhada",                cal: 215, prot: 28.0, carb: 0.0,  fat: 10.0 },
  { cat: "Carnes & Aves", nome: "Patinho moído cozido",            cal: 219, prot: 29.0, carb: 0.0,  fat: 11.0 },
  { cat: "Carnes & Aves", nome: "Contrafilé grelhado",             cal: 271, prot: 26.0, carb: 0.0,  fat: 18.0 },
  { cat: "Carnes & Aves", nome: "Maminha bovina",                  cal: 187, prot: 27.0, carb: 0.0,  fat: 8.5  },
  { cat: "Carnes & Aves", nome: "Fígado bovino",                   cal: 135, prot: 21.0, carb: 3.9,  fat: 3.6  },
  { cat: "Carnes & Aves", nome: "Peito de peru fatiado",           cal: 89,  prot: 18.0, carb: 1.0,  fat: 1.4  },
  { cat: "Carnes & Aves", nome: "Presunto cozido",                 cal: 145, prot: 18.0, carb: 1.3,  fat: 7.5  },
  { cat: "Carnes & Aves", nome: "Hambúrguer bovino",               cal: 295, prot: 17.0, carb: 0.0,  fat: 25.0 },

  // ── Peixes & Frutos do Mar ────────────────────────────────────────────────
  { cat: "Peixes & Frutos do Mar", nome: "Filé de tilápia grelhado",     cal: 128, prot: 26.0, carb: 0.0,  fat: 2.7  },
  { cat: "Peixes & Frutos do Mar", nome: "Salmão grelhado",              cal: 208, prot: 20.0, carb: 0.0,  fat: 13.0 },
  { cat: "Peixes & Frutos do Mar", nome: "Atum em água (lata)",          cal: 116, prot: 26.0, carb: 0.0,  fat: 1.0  },
  { cat: "Peixes & Frutos do Mar", nome: "Sardinha em óleo",             cal: 208, prot: 25.0, carb: 0.0,  fat: 11.0 },
  { cat: "Peixes & Frutos do Mar", nome: "Camarão grelhado",             cal: 99,  prot: 21.0, carb: 0.0,  fat: 1.1  },
  { cat: "Peixes & Frutos do Mar", nome: "Bacalhau cozido",              cal: 105, prot: 23.0, carb: 0.0,  fat: 1.0  },
  { cat: "Peixes & Frutos do Mar", nome: "Atum fresco grelhado",         cal: 184, prot: 30.0, carb: 0.0,  fat: 6.3  },
  { cat: "Peixes & Frutos do Mar", nome: "Merluza cozida",               cal: 79,  prot: 17.0, carb: 0.0,  fat: 0.7  },

  // ── Ovos & Laticínios ─────────────────────────────────────────────────────
  { cat: "Ovos & Laticínios", nome: "Ovo inteiro cozido",          cal: 155, prot: 13.0, carb: 1.1,  fat: 11.0 },
  { cat: "Ovos & Laticínios", nome: "Clara de ovo",                cal: 52,  prot: 11.0, carb: 0.7,  fat: 0.2  },
  { cat: "Ovos & Laticínios", nome: "Gema de ovo",                 cal: 322, prot: 16.0, carb: 3.6,  fat: 27.0 },
  { cat: "Ovos & Laticínios", nome: "Queijo cottage",              cal: 98,  prot: 11.0, carb: 3.4,  fat: 4.3  },
  { cat: "Ovos & Laticínios", nome: "Iogurte grego natural",       cal: 97,  prot: 9.0,  carb: 3.6,  fat: 5.0  },
  { cat: "Ovos & Laticínios", nome: "Iogurte natural desnatado",   cal: 56,  prot: 5.7,  carb: 7.7,  fat: 0.4  },
  { cat: "Ovos & Laticínios", nome: "Leite integral",              cal: 61,  prot: 3.2,  carb: 4.8,  fat: 3.3  },
  { cat: "Ovos & Laticínios", nome: "Leite desnatado",             cal: 35,  prot: 3.4,  carb: 5.0,  fat: 0.1  },
  { cat: "Ovos & Laticínios", nome: "Queijo minas frescal",        cal: 264, prot: 17.0, carb: 3.0,  fat: 21.0 },
  { cat: "Ovos & Laticínios", nome: "Queijo muçarela",             cal: 280, prot: 28.0, carb: 2.2,  fat: 17.0 },
  { cat: "Ovos & Laticínios", nome: "Queijo parmesão ralado",      cal: 431, prot: 38.0, carb: 3.2,  fat: 29.0 },
  { cat: "Ovos & Laticínios", nome: "Requeijão cremoso",           cal: 257, prot: 8.5,  carb: 3.9,  fat: 23.0 },
  { cat: "Ovos & Laticínios", nome: "Ricota",                      cal: 174, prot: 11.0, carb: 3.0,  fat: 13.0 },

  // ── Proteínas Vegetais & Suplementos ─────────────────────────────────────
  { cat: "Proteínas Vegetais", nome: "PTS (proteína de soja) seca",       cal: 336, prot: 52.0, carb: 27.0, fat: 2.0  },
  { cat: "Proteínas Vegetais", nome: "PTS (proteína de soja) cozida",     cal: 112, prot: 17.0, carb: 9.0,  fat: 0.7  },
  { cat: "Proteínas Vegetais", nome: "Tofu firme",                        cal: 76,  prot: 8.0,  carb: 1.9,  fat: 4.8  },
  { cat: "Proteínas Vegetais", nome: "Tofu sedoso",                       cal: 55,  prot: 5.0,  carb: 2.0,  fat: 3.0  },
  { cat: "Proteínas Vegetais", nome: "Tempeh",                            cal: 193, prot: 19.0, carb: 9.4,  fat: 11.0 },
  { cat: "Proteínas Vegetais", nome: "Edamame cozido",                    cal: 121, prot: 11.0, carb: 8.9,  fat: 5.2  },
  { cat: "Proteínas Vegetais", nome: "Seitan (glúten de trigo)",          cal: 120, prot: 25.0, carb: 4.0,  fat: 0.5  },
  { cat: "Proteínas Vegetais", nome: "Whey protein concentrado (pó)",     cal: 392, prot: 80.0, carb: 7.0,  fat: 5.0  },
  { cat: "Proteínas Vegetais", nome: "Caseína (pó)",                      cal: 370, prot: 82.0, carb: 4.0,  fat: 2.0  },
  { cat: "Proteínas Vegetais", nome: "Proteína de ervilha (pó)",          cal: 360, prot: 80.0, carb: 5.0,  fat: 2.0  },
  { cat: "Proteínas Vegetais", nome: "Proteína de arroz (pó)",            cal: 370, prot: 78.0, carb: 8.0,  fat: 2.5  },

  // ── Grãos & Cereais ───────────────────────────────────────────────────────
  { cat: "Grãos & Cereais", nome: "Arroz branco cozido",           cal: 130, prot: 2.7,  carb: 28.0, fat: 0.3  },
  { cat: "Grãos & Cereais", nome: "Arroz integral cozido",         cal: 111, prot: 2.6,  carb: 23.0, fat: 0.9  },
  { cat: "Grãos & Cereais", nome: "Feijão preto cozido",           cal: 132, prot: 8.9,  carb: 24.0, fat: 0.5  },
  { cat: "Grãos & Cereais", nome: "Feijão carioca cozido",         cal: 127, prot: 8.7,  carb: 22.0, fat: 0.5  },
  { cat: "Grãos & Cereais", nome: "Lentilha cozida",               cal: 116, prot: 9.0,  carb: 20.0, fat: 0.4  },
  { cat: "Grãos & Cereais", nome: "Grão-de-bico cozido",           cal: 164, prot: 8.9,  carb: 27.0, fat: 2.6  },
  { cat: "Grãos & Cereais", nome: "Aveia em flocos",               cal: 389, prot: 17.0, carb: 66.0, fat: 7.0  },
  { cat: "Grãos & Cereais", nome: "Quinoa cozida",                 cal: 120, prot: 4.4,  carb: 22.0, fat: 1.9  },
  { cat: "Grãos & Cereais", nome: "Macarrão integral cozido",      cal: 124, prot: 5.3,  carb: 26.0, fat: 0.5  },
  { cat: "Grãos & Cereais", nome: "Macarrão comum cozido",         cal: 158, prot: 5.8,  carb: 31.0, fat: 0.9  },
  { cat: "Grãos & Cereais", nome: "Cuscuz nordestino cozido",      cal: 112, prot: 2.6,  carb: 25.0, fat: 0.5  },
  { cat: "Grãos & Cereais", nome: "Tapioca simples",               cal: 358, prot: 0.2,  carb: 88.0, fat: 0.0  },
  { cat: "Grãos & Cereais", nome: "Fubá de milho",                 cal: 363, prot: 7.0,  carb: 78.0, fat: 2.3  },
  { cat: "Grãos & Cereais", nome: "Granola",                       cal: 471, prot: 10.0, carb: 64.0, fat: 20.0 },
  { cat: "Grãos & Cereais", nome: "Pão integral",                  cal: 247, prot: 13.0, carb: 41.0, fat: 4.2  },
  { cat: "Grãos & Cereais", nome: "Pão francês",                   cal: 300, prot: 8.0,  carb: 58.0, fat: 3.0  },
  { cat: "Grãos & Cereais", nome: "Pão de queijo (un. 50g)",       cal: 150, prot: 3.0,  carb: 22.0, fat: 6.0  },
  { cat: "Grãos & Cereais", nome: "Trigo sarraceno cozido",        cal: 92,  prot: 3.4,  carb: 20.0, fat: 0.6  },
  { cat: "Grãos & Cereais", nome: "Cevada cozida",                 cal: 123, prot: 2.3,  carb: 28.0, fat: 0.4  },

  // ── Tubérculos & Raízes ───────────────────────────────────────────────────
  { cat: "Tubérculos", nome: "Batata inglesa cozida",               cal: 87,  prot: 1.9,  carb: 20.0, fat: 0.1  },
  { cat: "Tubérculos", nome: "Batata-doce cozida",                  cal: 90,  prot: 2.0,  carb: 21.0, fat: 0.1  },
  { cat: "Tubérculos", nome: "Mandioca cozida",                     cal: 125, prot: 1.0,  carb: 30.0, fat: 0.2  },
  { cat: "Tubérculos", nome: "Inhame cozido",                       cal: 118, prot: 1.5,  carb: 28.0, fat: 0.1  },
  { cat: "Tubérculos", nome: "Milho cozido",                        cal: 108, prot: 3.4,  carb: 25.0, fat: 1.3  },
  { cat: "Tubérculos", nome: "Beterraba cozida",                    cal: 44,  prot: 1.7,  carb: 10.0, fat: 0.2  },
  { cat: "Tubérculos", nome: "Cenoura crua",                        cal: 41,  prot: 0.9,  carb: 10.0, fat: 0.2  },

  // ── Vegetais ──────────────────────────────────────────────────────────────
  { cat: "Vegetais", nome: "Brócolis cozido",                       cal: 35,  prot: 2.4,  carb: 7.2,  fat: 0.4  },
  { cat: "Vegetais", nome: "Espinafre cozido",                      cal: 23,  prot: 3.0,  carb: 3.8,  fat: 0.3  },
  { cat: "Vegetais", nome: "Couve refogada",                        cal: 36,  prot: 2.1,  carb: 7.3,  fat: 0.4  },
  { cat: "Vegetais", nome: "Couve-flor cozida",                     cal: 23,  prot: 1.9,  carb: 4.4,  fat: 0.2  },
  { cat: "Vegetais", nome: "Abobrinha cozida",                      cal: 17,  prot: 1.2,  carb: 3.5,  fat: 0.2  },
  { cat: "Vegetais", nome: "Berinjela cozida",                      cal: 35,  prot: 0.8,  carb: 8.7,  fat: 0.2  },
  { cat: "Vegetais", nome: "Abóbora cozida",                        cal: 26,  prot: 1.0,  carb: 6.5,  fat: 0.1  },
  { cat: "Vegetais", nome: "Tomate",                                cal: 18,  prot: 0.9,  carb: 3.9,  fat: 0.2  },
  { cat: "Vegetais", nome: "Alface",                                cal: 15,  prot: 1.4,  carb: 2.9,  fat: 0.2  },
  { cat: "Vegetais", nome: "Pepino",                                cal: 16,  prot: 0.7,  carb: 3.6,  fat: 0.1  },
  { cat: "Vegetais", nome: "Repolho cru",                           cal: 25,  prot: 1.3,  carb: 5.8,  fat: 0.1  },
  { cat: "Vegetais", nome: "Pimentão vermelho",                     cal: 31,  prot: 1.0,  carb: 6.0,  fat: 0.3  },
  { cat: "Vegetais", nome: "Cebola",                                cal: 40,  prot: 1.1,  carb: 9.3,  fat: 0.1  },
  { cat: "Vegetais", nome: "Aspargo cozido",                        cal: 20,  prot: 2.2,  carb: 3.9,  fat: 0.2  },
  { cat: "Vegetais", nome: "Vagem cozida",                          cal: 31,  prot: 1.8,  carb: 7.1,  fat: 0.1  },
  { cat: "Vegetais", nome: "Chuchu cozido",                         cal: 24,  prot: 1.0,  carb: 5.5,  fat: 0.2  },

  // ── Frutas ────────────────────────────────────────────────────────────────
  { cat: "Frutas", nome: "Banana",                                  cal: 89,  prot: 1.1,  carb: 23.0, fat: 0.3  },
  { cat: "Frutas", nome: "Maçã",                                    cal: 52,  prot: 0.3,  carb: 14.0, fat: 0.2  },
  { cat: "Frutas", nome: "Mamão papaya",                            cal: 43,  prot: 0.5,  carb: 11.0, fat: 0.3  },
  { cat: "Frutas", nome: "Laranja",                                 cal: 47,  prot: 0.9,  carb: 12.0, fat: 0.1  },
  { cat: "Frutas", nome: "Morango",                                 cal: 32,  prot: 0.7,  carb: 7.7,  fat: 0.3  },
  { cat: "Frutas", nome: "Uva",                                     cal: 69,  prot: 0.7,  carb: 18.0, fat: 0.2  },
  { cat: "Frutas", nome: "Melancia",                                cal: 30,  prot: 0.6,  carb: 7.6,  fat: 0.2  },
  { cat: "Frutas", nome: "Abacaxi",                                 cal: 50,  prot: 0.5,  carb: 13.0, fat: 0.1  },
  { cat: "Frutas", nome: "Manga",                                   cal: 60,  prot: 0.8,  carb: 15.0, fat: 0.4  },
  { cat: "Frutas", nome: "Abacate",                                 cal: 160, prot: 2.0,  carb: 9.0,  fat: 15.0 },
  { cat: "Frutas", nome: "Kiwi",                                    cal: 61,  prot: 1.1,  carb: 15.0, fat: 0.5  },
  { cat: "Frutas", nome: "Goiaba",                                  cal: 68,  prot: 2.6,  carb: 14.0, fat: 1.0  },
  { cat: "Frutas", nome: "Maracujá (polpa)",                        cal: 97,  prot: 2.2,  carb: 23.0, fat: 0.7  },
  { cat: "Frutas", nome: "Açaí puro (polpa)",                       cal: 247, prot: 2.0,  carb: 7.0,  fat: 25.0 },
  { cat: "Frutas", nome: "Caju",                                    cal: 43,  prot: 0.8,  carb: 10.0, fat: 0.3  },
  { cat: "Frutas", nome: "Melão",                                   cal: 34,  prot: 0.8,  carb: 8.2,  fat: 0.2  },

  // ── Oleaginosas & Gorduras ────────────────────────────────────────────────
  { cat: "Oleaginosas & Gorduras", nome: "Amendoim torrado",        cal: 567, prot: 26.0, carb: 16.0, fat: 49.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Pasta de amendoim",       cal: 588, prot: 25.0, carb: 20.0, fat: 50.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Castanha-do-pará",        cal: 656, prot: 14.0, carb: 12.0, fat: 66.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Castanha de caju",        cal: 553, prot: 18.0, carb: 30.0, fat: 44.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Amêndoas",                cal: 579, prot: 21.0, carb: 22.0, fat: 50.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Nozes",                   cal: 654, prot: 15.0, carb: 14.0, fat: 65.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Chia",                    cal: 486, prot: 17.0, carb: 42.0, fat: 31.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Linhaça dourada",         cal: 534, prot: 18.0, carb: 29.0, fat: 42.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Semente de abóbora",      cal: 559, prot: 30.0, carb: 11.0, fat: 49.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Azeite de oliva",         cal: 884, prot: 0.0,  carb: 0.0,  fat: 100.0},
  { cat: "Oleaginosas & Gorduras", nome: "Óleo de coco",            cal: 862, prot: 0.0,  carb: 0.0,  fat: 100.0},
  { cat: "Oleaginosas & Gorduras", nome: "Manteiga",                cal: 717, prot: 0.9,  carb: 0.1,  fat: 81.0 },
  { cat: "Oleaginosas & Gorduras", nome: "Ghee (manteiga clarificada)", cal: 900, prot: 0.0, carb: 0.0, fat: 100.0},

  // ── Extras & Outros ───────────────────────────────────────────────────────
  { cat: "Extras", nome: "Mel",                                     cal: 304, prot: 0.3,  carb: 82.0, fat: 0.0  },
  { cat: "Extras", nome: "Açúcar refinado",                         cal: 387, prot: 0.0,  carb: 100.0,fat: 0.0  },
  { cat: "Extras", nome: "Chocolate 70% cacau",                     cal: 598, prot: 8.0,  carb: 46.0, fat: 43.0 },
  { cat: "Extras", nome: "Chocolate ao leite",                      cal: 535, prot: 8.0,  carb: 60.0, fat: 30.0 },
  { cat: "Extras", nome: "Leite de coco (caixinha)",                cal: 230, prot: 2.3,  carb: 5.5,  fat: 23.0 },
  { cat: "Extras", nome: "Creme de leite",                          cal: 312, prot: 2.5,  carb: 3.0,  fat: 32.0 },
  { cat: "Extras", nome: "Molho de tomate simples",                 cal: 45,  prot: 1.5,  carb: 8.5,  fat: 0.8  },
  { cat: "Extras", nome: "Maionese",                                cal: 680, prot: 1.2,  carb: 3.2,  fat: 74.0 },
];
